{
 "title": "KumoMTA",
 "description": "Monitor your KumoMTA instances",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(memory_limit,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deliveries (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs/s" } },
   "targets": [
    {
     "expr": "irate(total_messages_delivered{exported_service!=\"smtp_client\", instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "{{exported_service}} - {{instance}}"
    },
    {
     "expr": "irate(total_messages_delivered{exported_service=\"smtp_client\", instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "Total - {{instance}}"
    }
   ]
  },
  {
   "title": "Throughput (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs/s" } },
   "targets": [
    {
     "expr": "irate(total_messages_delivered{exported_service=\"smtp_client\", instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "Outbound - {{instance}}"
    },
    {
     "expr": "irate(total_messages_received{exported_service=\"esmtp_listener\", instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "Inbound - {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "connection_count{instance=~\"$Host\"}",
     "legendFormat": "{{exported_service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(total_messages_transfail{instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "4xx {{exported_service}} - {{instance}}"
    },
    {
     "expr": "irate(total_messages_fail{instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "5xx {{exported_service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ready Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "ready_count{instance=~\"$Host\"}",
     "legendFormat": "{{exported_service}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Scheduled Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "scheduled_queue_count{instance=~\"$Host\"}",
     "legendFormat": "{{queue}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "message_count{instance=~\"$Host\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "message_data_resident_count{instance=~\"$Host\"}",
     "legendFormat": "Data Resident - {{instance}}"
    },
    {
     "expr": "message_meta_resident_count{instance=~\"$Host\"}",
     "legendFormat": "Meta Resident - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_usage{instance=~\"$Host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lua Contexts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "lua_count{instance=~\"$Host\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "lua_spare_count{instance=~\"$Host\"}",
     "legendFormat": "Spare - {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound SMTP Transaction Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 }
  },
  {
   "title": "avg lua event latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(lua_event_latency_sum{event!~\"(init|pre_init)\", instance=~\"$Host\"}[$__rate_interval]) / irate(lua_event_latency_count{event!~\"(init|pre_init)\", instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "{{event}} {{instance}}"
    }
   ]
  },
  {
   "title": "lua event rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(lua_event_latency_count{instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "{{event}} {{instance}}"
    }
   ]
  },
  {
   "title": "Threads In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "thread_pool_size{instance=~\"$Host\"} - thread_pool_parked{instance=~\"$Host\"}",
     "legendFormat": "{{pool}} {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_free_percent{instance=~\"$Host\"}",
     "legendFormat": "{{name}} space {{instance}}"
    },
    {
     "expr": "disk_free_inodes_percent{instance=~\"$Host\"}",
     "legendFormat": "{{name}} inodes {{instance}}"
    }
   ]
  },
  {
   "title": "p95 lua event latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, event, instance) (irate(lua_event_latency_bucket{event!~\"(init|pre_init)\", instance=~\"$Host\"}[$__rate_interval])))",
     "legendFormat": "{{event}} {{instance}}"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "timeseries",
   "description": "Gives a sense of where things are taking time. Have non-zero values here is not necessarily bad, but tall and sustained values is something to look into",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "clamp_min(irate(lua_event_started{instance=~\"$Host\"}[$__rate_interval]) - irate(lua_event_latency_count{instance=~\"$Host\"}[$__rate_interval]), 0)",
     "legendFormat": "{{event}} {{instance}}"
    },
    {
     "expr": "irate(log_submit_latency_count{instance=~\"$Host\"}[$__rate_interval])",
     "legendFormat": "log_submit_latency_count {{logger}} {{instance}}"
    },
    {
     "expr": "clamp_min(irate(dkim_signer_cache_lookup_count{instance=~\"$Host\"}[$__rate_interval]) - (irate(dkim_signer_cache_hit{instance=~\"$Host\"}[$__rate_interval]) + irate(dkim_signer_cache_miss{instance=~\"$Host\"}[$__rate_interval])), 0)",
     "legendFormat": "dkim_signer"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(memoize_cache_miss_count{instance=~\"$Host\"}[$__rate_interval])\n  / on() group_left()\nsum(increase(memoize_cache_lookup_count{instance=~\"$Host\"}[$__rate_interval]))",
     "legendFormat": "{{cache_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "p50 lua event latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, event, instance) (irate(lua_event_latency_bucket{event!~\"(init|pre_init)\", instance=~\"$Host\"}[$__rate_interval])))",
     "legendFormat": "{{event}} {{instance}}"
    }
   ]
  }
 ]
}